### PR TITLE
Throw error if text value is not valid

### PR DESCRIPTION
**Pull request by saikrishna321**
Address: #751

### CODE REVIEW

**Comment by saikrishna321** [comment]
@zabil  and @sriv I have fixed all the review comments. Can you pls look at it now?

**Comment by saikrishna321** [comment]
Sorry, found something, will fix it!!

**Comment by negiDharmendra** [comment]
@saikrishna321 FTs are still [failing](https://getgauge.visualstudio.com/Taiko/_build/results?buildId=1180).

**Comment by saikrishna321** [comment]
@gaugebot recheck the pull request.

**Pull request closed without merging**
