### PR TITLE
Add raspberry pi trouble shooting section

### PR DESCRIPTION
**Pull request by edouardmenayde**
Specifies the steps needed to be followed to use taiko on a raspberry pi running raspbian.

### CODE REVIEW

**Comment by Apoorva-GA** [comment]
@edouardmenayde Thanks for your contribution!!
Could you please sign the CLA so that we can merge this PR to master.

**Comment by edouardmenayde** [comment]
@Apoorva-GA Already did it, everytime I get redirected to github which says ` gaugebot is a private GitHub App. `.

**Comment by negiDharmendra** [comment]
@gaugebot recheck

**Comment by NivedhaSenthil** [comment]
@gaugebot recheck the pull request.

**Comment by NivedhaSenthil** [comment]
Can you please do it again ?  the CLA bot is fixed now

**Comment by edouardmenayde** [comment]
@gaugebot recheck the pull request.

**Pull request merged**
