### PR TITLE
Making DropDownWrapper extend MultiValueWrapper

### PR DESCRIPTION
**Pull request by fmpanelli**
`DropDownWrapper `previously extended `ValueWrapper `which has a method `value()` returning `Promise<string>`.

With this commit `DropDownWrapper` extends a new `MultiValueWrapper` which has a method `values()` returning `Promise<string | string[] | number[]>`.

The `ValueWrapper` remains as it is for the elements that actually implement that behavior such as `ColorWrapper`, `TextBoxWrapper`, etc.

Related to issue #1652

### CODE REVIEW

**Comment by zabil** [comment]
I see that this pull request changes an existing method `value` to `values`. This breaks backward compatibility for tests that already use `value`.

In the wild, I see more usage of single value dropdown than multi value dropdown. So most of the usage of `values` will probably return only one value. Also, having one method of getting value for a control like `text` makes it easier to discover.

From the tests I see that `values` works for return one value as well an array of values. Can we rename the method to `value`? 

Internally, I think it's ok to use 'multiValueWrapper.js' to get this behaviour.

**Comment by fmpanelli** [comment]
> I see that this pull request changes an existing method `value` to `values`. This breaks backward compatibility for tests that already use `value`.
> 
> In the wild, I see more usage of single value dropdown than multi value dropdown. So most of the usage of `values` will probably return only one value. Also, having one method of getting value for a control like `text` makes it easier to discover.
> 
> From the tests I see that `values` works for return one value as well an array of values. Can we rename the method to `value`?
> 
> Internally, I think it's ok to use 'multiValueWrapper.js' to get this behaviour.

Hi Zabil, thank you for you swift feedback.

That's a very good point. The fundamental fact is that we are changing the external behavior of the `DropDown` element and we are trying to do that as backward-compatible as possible.

I get your approach. It is more backward-compatible than my first proposition but it will still break callers in two cases:
1. if you have a Typescript caller that makes something like the following:
```
async function myDropDownValue(): Promise<string>{
  const myDropdown = dropDown('Vehicle:');
  await myDropdown.select(['Car','Van']);
  return await myDropdown.value(); // type error: Promise<string|string[]|number[]> is not assignable to Promise<string>
}
```
2. if you have some javascript calling `value()` and expecting a string, but actually receiving an array (albeit I am not 100% sure if this is really possible)

Let me propose a third approach which is even more backward-compatible and it is cleaner from the point of view of types.

We may want to have 2 methods in `MultiValueWrapper`:
- `value(): string` which always return 1 value as `string` (if there are more, we may want to return the first one or to throw)
- `values(): string[]` which returns all the values
In this case `MultiValueWrapper` naturally extends `ValueWrapper` making the transition even smoother.

What do you think?

**Comment by zabil** [comment]
> We may want to have 2 methods in MultiValueWrapper:

Yes, we did think about it in the initial PR and I suggested merging the two methods. But I looks like that's a cleaner approach taking typescript into account. So yes, let's do that.

**Comment by zabil** [comment]
One more thing. Won't fixing the signature of the method in the sample you mentioned fix the compilation issue? Do you See an issue upstream when calling `myDropDownValue`? I am assuming it is ok to expect the same type of `value`

```
async function myDropDownValue(): Promise<string|string[]|number[]> {
  const myDropdown = dropDown('Vehicle:');
  await myDropdown.select(['Car','Van']);
  return await myDropdown.value(); // type error: Promise<string|string[]|number[]> is not assignable to Promise<string>
}
```

**Comment by fmpanelli** [comment]
Yes Zabil, changing the calling code will fix it.
My point is that it is a breaking change, meaning that you have to change the client code to make it work properly.
Of course you need to change not only the method `myDropDownValue` but also its callers.

**Comment by zabil** [comment]
> My point is that it is a breaking change

I get it now. It breaks for consumers of the original typescript reference and that shouldn't happen. Two method approach is the best for current javascript and typescript users.

**Comment by NivedhaSenthil** [comment]
@fmpanelli any updates ?

**Comment by zabil** [comment]
Closing this to prevent accidental merges as this is a breaking change. Will re-open when the required changes are pushed.

**Pull request closed without merging**
