### PR TITLE
Text match should work on collapsed consecutive whitespaces

### PR DESCRIPTION
**Pull request by yashkumar18**
Detailed explanation [here](https://github.com/getgauge/taiko/issues/2028).

### CODE REVIEW

**Comment by zabil** [comment]
Thanks for the PR! will be reviewing this soon.

**Review by NivedhaSenthil — APPROVED** [review]

**Comment by NivedhaSenthil** [comment]
LGTM

**Comment by yashkumar18** [comment]
@NivedhaSenthil @zabil 
Could you help unblock the workflows

Getting this message - `First-time contributors need a maintainer to approve running workflows`

**Comment by yashkumar18** [comment]
@NivedhaSenthil @zabil Thanks for all the help here. 
Looks like we are good to go, please merge.

**Pull request merged**
