### PR TITLE
Fix the quotation mark

### PR DESCRIPTION
**Pull request by CzarScar**
Fix the quotation mark. In case anyone who wants to copy command from the Webpage or README will execute the command failed.

### CODE REVIEW

**Comment by CzarScar** [comment]
@gaugebot recheck the pull request.

**Comment by CzarScar** [comment]
The CI just failed because of the Network issue. Not sure why. Could someone help me to check or rebuild?

**Comment by zabil** [comment]
Merging this as it's not connected the build failure.
Thanks @CzarScar!

**Comment by CzarScar** [comment]
Cool, I can copy the command from the Taiko website and run directly now.

**Pull request merged**
