### PR TITLE
mask text when write API is used with into

### PR DESCRIPTION
**Pull request by saikrishna321**
Address: #740

### CODE REVIEW

**Comment by Debashis9012** [comment]
@saikrishna321  I have added test for it.
Its available in branch [Test for hide text option](https://github.com/getgauge/taiko/tree/writeapihideText-test).

**Comment by saikrishna321** [comment]
@Debashis9012 I don't see any tests in the branch. You can add test to the current PR if you're okay. Is not I can do that 😸

**Comment by Debashis9012** [comment]
@saikrishna321 Hey sorry for the wrong branch. The above branch which i have shared before it was a part of #740 fix and it does not have tests. Please feel free to add tests.

**Comment by BugDiver** [comment]
@saikrishna321 These changes are available via 93c82f16f008c7a24f1060c9eb4a00e3a7cb97a8.
Closing the Pull request.

**Pull request closed without merging**
