### PR TITLE
Bump version 1.3.6

### PR DESCRIPTION
**Pull request by marques-work**
Can we do a release to make the macOS arm64 enhancement available?

cc: @zabil
cc: @NivedhaSenthil

### CODE REVIEW

**Comment by zabil** [comment]
@marques-work Yes! 

Will do it next week after seeing if someone pulls from master to give it a spin and report issues :)

**Comment by marques-work** [comment]
Maybe wait for #2670 before bumping? `documentation` package just released an update that fixes a critcial vuln.

**Review by zabil — APPROVED** [review]

**Comment by marques-work** [comment]
Thanks @zabil -- can we tag/cut a release so it's avail on npm? Or did you want to wait a little bit for any issues to come in?

**Comment by zabil** [comment]
Oh dang, I was supposed to label that as a release candidate for it to automatically trigger the release. So need to see good I can trigger it manually

**Comment by zabil** [comment]
@marques-work if you don't mind can you send another pr bumping up the version to 1.3.7?

**Comment by marques-work** [comment]
I can -- do you think it would be better do revert to 1.3.5 and then bump up again so we don't skip a version number? Or is it just better to go to 1.3.7?

**Comment by marques-work** [comment]
actually, 1.3.7 is just easier -- why go through 2 PRs right?

**Pull request merged**
