### PR TITLE
Change waitFor() internal call from .get() to .elements()

### PR DESCRIPTION
**Pull request by moogleberry**
https://github.com/getgauge/taiko/issues/1004
Changed `waitFor()` internal call from `.get()` to `.elements()` when using a selector due to `.get()` being deprecated.

### CODE REVIEW

**Comment by saikrishna321** [comment]
@moogleberry Can you please resolve the conflicts?

**Comment by moogleberry** [comment]
> @moogleberry Can you please resolve the conflicts?

resolved

**Comment by negiDharmendra** [comment]
@moogleberry Can you please resolve the conflicts?

**Comment by moogleberry** [comment]
@negiDharmendra the bot says "This branch has no conflicts with the base branch"

**Pull request merged**
