### PR TITLE
Add option to select hidden image

### PR DESCRIPTION
**Pull request by sivaranjanidev**
Part of #811

Same approach as #899

### CODE REVIEW

**Comment by BugDiver** [comment]
Please resolve the conflicts with the master.

**Comment by sivaranjanidev** [comment]
> @sivaranjanidev Please resolve the conflicts with the master.

I will resolve it today

**Comment by sivaranjanidev** [comment]
I have resolved the commit and pushed again. Kindly review and merge the changes.

**Comment by BugDiver** [comment]
@sivaranjanidev Thanks for the pull request. 🎉 🎉

**Comment by sivaranjanidev** [comment]
@BugDiver This is My First PR 🎉 🎉.. Thank u so much

**Pull request merged**
