### PR TITLE
#1134 Case insensitive selectors

### PR DESCRIPTION
**Pull request by gabrielpeixinho**
Guys, I will appreciate your feedback.

Ps. Some indentations were made by git-hook/lint (checkbox.test.js)

### CODE REVIEW

**Comment by sriv** [comment]
The change looks ok. The linting diff is a bit confusing but I believe it is because of https://github.com/getgauge/taiko/pull/1137/files#diff-63d0e1dabb2caa7a843c2fb10480d3a8R24 (the `forEach` creates one more level of nesting).

Let me know when you are done, and we can look at merging this.

**Comment by gabrielpeixinho** [comment]
> The change looks ok. The linting diff is a bit confusing but I believe it is because of https://github.com/getgauge/taiko/pull/1137/files#diff-63d0e1dabb2caa7a843c2fb10480d3a8R24 (the `forEach` creates one more level of nesting).
> 
> Let me know when you are done, and we can look at merging this.

I usually rebase my commits, squashing and changing commit messages, but some work already been merged on to PR-branch. How to handle this situation?

Thank you.

**Comment by sriv** [comment]
You should be able to pull this branch using `https://github.com/getgauge/taiko` as the origin.

See https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork for reference.

**Comment by gabrielpeixinho** [comment]
History rewrite and sync are done. Tks again!

**Comment by sriv** [comment]
thanks @gabrielpeixinho

**Pull request merged**
