### PR TITLE
#1203 return status code from goto

### LINKED ISSUE #1203: Capability to retrieve status code from Goto()
This is a request for a new feature

### Requested feature
Add capability to be able to pull out the status code from Goto(). Helps in some instances. 
Some more context to where folks might find this useful: 
<[Spectrum Chat - Taiko](https://spectrum.chat/taiko/general/i-am-having-issues-with-using-goto-when-the-page-redirects-it-doesnt-seem-to-detect-redirects-and-wait-for-redirect-to-complete-before-moving-onto-the-next-step~310440ec-9195-4928-814c-f764313c37c5)>

### Actual behavior
Goto() does not relay what the status code of the Goto() operation is. 

### Versions
```
node version: v13.12.0
taiko version: 1.0.6
```

### PR DESCRIPTION
**Pull request by NivedhaSenthil**
Signed-off-by: NivedhaSenthil <nivedhasenthil@gmail.com>
Fixes #1203

### CODE REVIEW

**Comment by zabil** [comment]
I think this should wrapped in a json string for example.

```
response = goto("google.com")
if(!response.ok) { // boolean, true for 200 and false for rest, must handle redirects
 console.log(response.status)
}
```

**Comment by NivedhaSenthil** [comment]
```
> goto("gauge.org/")
 value: {
  redirectedResponse: [
    {
      url: 'http://gauge.org/',
      status: 301,
      statusText: 'Moved Permanently'
    }
  ],
  url: 'https://gauge.org/',
  status: 200,
  statusText: ''
}
```

sample response looks like above

**Comment by zabil** [comment]
Can you please make this

```
> goto("gauge.org/")
 value: {
  redirectedResponse: [
    {
      url: 'http://gauge.org/',
      status : { code: 301,
                    text: 'Moved Permanently'
                 }
    }
  ],
  url: 'https://gauge.org/',
  status: { code: 200,
                  text: ''
               }
}
```

Are the url's going to be the same (in the example `http://gauge.org`) even if it's been redirected for example from `taiko.gauge.org` -> 'taiko.dev'

**Comment by NivedhaSenthil** [comment]
Response for `taiko.gauge.org`
```
> goto("taiko.gauge.org")
 value: {
  redirectedResponse: [
    {
      url: 'http://taiko.gauge.org/',
      status: { code: 301, text: 'Moved Permanently' }
    },
    {
      url: 'https://taiko.gauge.org/',
      status: { code: 301, text: '' }
    },
    {
      url: 'http://taiko.dev/',
      status: { code: 307, text: 'Internal Redirect' }
    }
  ],
  url: 'https://taiko.dev/',
  status: { code: 200, text: '' }
}
```

**Comment by zabil** [comment]
Can we also update the documentation for the goto api. Preferably an example showing the usage.

**Comment by NivedhaSenthil** [comment]
updated docs 👍

**Pull request merged**
