### PR TITLE
329 set local storage

### PR DESCRIPTION
**Pull request by jaydeepc**

### CODE REVIEW

**Comment by jaydeepc** [comment]
supports #329

**Comment by NivedhaSenthil** [comment]
IMO it is better to expose `addScriptToEvaluateOnNewDocument` separately so that user can add any scripts to be evaluated on new document load, and have apis to support get, set and delete localStorage .. thoughts ?

**Comment by jaydeepc** [comment]
@NivedhaSenthil I thought so. But that was thinking about security consequences. (If there can be any, dint give it too much thought, but I am always a bit picky about giving full control :)). What do you think?

**Comment by NivedhaSenthil** [comment]
Any scripts to be evaluated can be added via `evaluate` api or by accessing CRI apis directly currently.
with `addToLocalStorage` user will expect values given to be added to localStorage in current context which will not happen with the current implementation, it will get added only when there is a new document load and it will try to add for all new document load  so user will have to add it even before `goto` call which may not be what user will expect from `addToLocalStorage`.

We need to give a broader thought for security, currently chromium should be handling major security
concerns like CORS etc and script is run in sandboxed environment  off-process from chromium restricting access to other processes unless user disables it manually.

**Pull request closed without merging**
