### PR TITLE
Make openTab to open a new tab in current browser context

### LINKED ISSUE #1282: openTab should open a tab on active window
### Expected behavior
openTab should open a tab on currently active window

### Actual behavior
opens a tab on default window

### Steps to reproduce
1. openBrowser()
2. openIncognitoBrowser()
3. openTab()

### Versions
```
taiko 1.0.11
```

### PR DESCRIPTION
**Pull request by NivedhaSenthil**
fixes #1282 

- Remove BrowserContext file
- Move browser context logic to target handler
- Make target handler maintain states of current target, current browser context and the connected  special target.
- Use special target to create new targets for both openIncognitoWindow and openTab
- Move waiting for target creation during openBrowser logic to target handler
- Make closeIncognitoWindow close the whole window instead of single tab
- Fix closeTab without parameter by using currentTarget 
- Move connect host, port and browserDebugUrl to config to cleanup globals in taiko.js and to avoid passing those states around
- Remove unnecessary options.window in connections
- Remove `incognito:true` state since all new windows are incognito by default
- Fix mocks in tests

### CODE REVIEW

**Comment by zabil** [comment]
There seems to be a regression in the unique tab identifier functionality.

```
const { openBrowser, goto, openTab, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto('google.com');
        await openTab('http://github.com', { name: 'github'});
        await openTab('http://github.com', { name: 'github'});
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();

```

I am sure there was a test for it. However with this PR is allows tabs with the same identifier.

```
➜  taiko git:(master) node bin/taiko.js

Version: 1.0.25 (Chromium: 87.0.4279.0)
Type .api for help and .exit to quit

> openBrowser()
 ✔ Browser opened
> .exit
 ✔ Browser closed
➜  taiko git:(master) vi test-script.js
➜  taiko git:(master) node bin/taiko.js test-script.js
 ✔ Browser opened
 ✔ Navigated to URL http://google.com
 ✔ Opened tab with URL http://github
Error: There is a window or tab already registered with the name 'github' please use another name.
    at module.exports.openTab (/Users/zabilcm/Projects/taiko/lib/taiko.js:610:11)
    at module.exports.<computed> (/Users/zabilcm/Projects/taiko/lib/taiko.js:3336:36)
    at global.<computed> (/Users/zabilcm/Projects/taiko/bin/runFile.js:38:37)
    at /Users/zabilcm/Projects/taiko/test-script.js:7:15
 ✔ Browser closed


➜  taiko git:(master) git checkout fix_openTab
Switched to branch 'fix_openTab'
Your branch is up to date with 'origin/fix_openTab'.
➜  taiko git:(fix_openTab) node bin/taiko.js test-script.js
 ✔ Browser opened
 ✔ Navigated to URL http://google.com
 ✔ Opened tab with URL http://github
 ✔ Opened tab with URL http://github
 ✔ Browser closed
➜  taiko git:(fix_openTab)
```

**Comment by NivedhaSenthil** [comment]
fixed the above case, seems the test was giving false positive result as it was running on mocked targetHandler

**Comment by zabil** [comment]
The following script gives an error. 

```
const { openBrowser, goto, openTab, openIncognitoWindow, switchTo, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto('google.com');
        await openTab('github.com', { name: 'github' });
        await openIncognitoWindow({name: 'taiko'});
        await openIncognitoWindow({name: 'gauge'});
        await switchTo(/google.com/);
        await openTab(); 
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();

```

```
✔ Browser opened
 ✔ Navigated to URL http://google.com
 ✔ Opened tab with URL http://github.com
 ✔ Incognito window opened with name taiko
 ✔ Incognito window opened with name gauge
 ✔ Switched to tab matching /google.com/
ProtocolError: Failed to find browser context with id F6EC1A74D930119EB4DA39DD86DDB586
    at /Users/zabilcm/Projects/taiko/node_modules/chrome-remote-interface/lib/chrome.js:93:35
    at Chrome._handleMessage (/Users/zabilcm/Projects/taiko/node_modules/chrome-remote-interface/lib/chrome.js:256:17)
    at WebSocket.<anonymous> (/Users/zabilcm/Projects/taiko/node_modules/chrome-remote-interface/lib/chrome.js:234:22)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/Users/zabilcm/Projects/taiko/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/Users/zabilcm/Projects/taiko/node_modules/ws/lib/receiver.js:436:14)
    at /Users/zabilcm/Projects/taiko/node_modules/ws/lib/receiver.js:393:23
    at /Users/zabilcm/Projects/taiko/node_modules/ws/lib/permessage-deflate.js:306:9
    at /Users/zabilcm/Projects/taiko/node_modules/ws/lib/permessage-deflate.js:385:7 {
  request: {
    method: 'Target.createTarget',
    params: {
      url: 'about:blank',
      browserContextId: 'F6EC1A74D930119EB4DA39DD86DDB586'
    }
  },
  response: {
    code: -32000,
    message: 'Failed to find browser context with id F6EC1A74D930119EB4DA39DD86DDB586'
  }
}
 ✔ Browser closed
```

On a side note. The error should be wrapped inside a better message. For e.g. 
```
Failed to open a new tab. 
Failed to find browser context with id 5730624CDD5DA5BB9705E38D2FFC1630,
```

**Comment by zabil** [comment]
Another case that is not working as is closing incognito window.

```
const { openBrowser, goto, openTab, openIncognitoWindow, switchTo, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto('google.com');
        await openTab('github.com', { name: 'github' });
        await openIncognitoWindow({name: 'gauge'});
        await goto('taiko.dev');
        await switchTo(/google.com/);
	await closeIncognitoWindow('gauge');
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```

This hangs for some reason and I need to ctrl+c out of the run or in the REPL
```
node bin/taiko.js close-incog.js
 ✔ Browser opened
 ✔ Navigated to URL http://google.com
 ✔ Opened tab with URL http://github.com
 ✔ Incognito window opened with name gauge
 ✔ Navigated to URL http://taiko.dev
 ✔ Switched to tab matching /google.com/
^C⏎
```

**Comment by NivedhaSenthil** [comment]
@zabil have fixed the above cases please verify again.

**Review by zabil — APPROVED** [review]

**Pull request merged**
