### PR TITLE
Add Option to pass select hidden Element attribute for Button Selector

### PR DESCRIPTION
**Pull request by jayandran-Sampath**
part of #811

### CODE REVIEW

**Comment by BugDiver** [comment]
@jayandran-Sampath Can you please resolve the conflicts with master rebase it with the same

**Comment by jayandran-Sampath** [comment]
@gaugebot recheck the pull request.

**Comment by BugDiver** [comment]
@gaugebot recheck the pull request.

**Comment by BugDiver** [comment]
@jayandran-Sampath  Thanks for the pull request 🎉 🎉

**Pull request merged**
