### PR TITLE
Bump version 1.3.7

### PR DESCRIPTION
**Pull request by marques-work**
@zabil here you go -- don't forget the label ;).

### CODE REVIEW

**Review by zabil — APPROVED** [review]

**Comment by zabil** [comment]
It's supposed to trigger this pipeline https://github.com/getgauge/taiko/actions/workflows/release.yml

And for some reason that's not happening. Need to 🔍

**Comment by marques-work** [comment]
Does it need to be tagged too for it to run or does that happen automatically during the build?

**Comment by zabil** [comment]
There's a [bot](https://github.com/getgauge/gauge-bot/blob/6aa40f28cface96af1481c2ce6e71ba8d3f05137/src/prHandler.js#L18) that monitors all PR merges and triggers the release workflow. I suspect the bot maybe down.

**Comment by zabil** [comment]
I think I know why.
Gauge bot was running on heroku at https://gauge-bot.herokuapp.com

And they've [stopped supporting](https://blog.heroku.com/next-chapter#:~:text=Starting%20November%2028%2C%202022%2C%20we%20plan%20to%20stop%20offering%20free%20product%20plans%20and%20plan%20to%20start%20shutting%20down%20free%20dynos%20and%20data%20services.%20We%20will%20be%20sending%20out%20a%20series%20of%20email%20communications%20to%20affected%20users.) a free tier.

Will need to make alternate arrangements for automatic release.

**Comment by marques-work** [comment]
Ah I see. That makes sense. Maybe a google function in the always free tier?

**Comment by zabil** [comment]
Gauge bot is built using probot and it has an option to for deployment as [netlify function](https://probot.github.io/docs/deployment/#netlify-functions) 

This looks like the best option as netlify graciously gave us an open source license and it's free. We can also use github logins to manage access.

[Netlify functions](https://www.netlify.com/blog/2021/12/11/serverless-functions-made-simple-just-add-files/#:~:text=How%20to%20add%20serverless%20functions,That's%20it.) can pull from the https://github.com/getgauge/gauge-bot repo. Will explore that option.

**Comment by marques-work** [comment]
Nice! That’s very cool of them 👍🏼

**Comment by zabil** [comment]
Still working on a [PR](https://github.com/getgauge/gauge-bot/pull/32) to fix this on Gauge bot. Will be a bit slow because of the holiday season.

**Comment by zabil** [comment]
@marques-work 
Managed to deploy the bot as a netlify function at https://bot.gauge.org

Can you raise a PR upgrading packages and the version number? I'll label it as a release candidate and merge it to trigger a release.

**Comment by marques-work** [comment]
Sure, thanks Zabil!

**Pull request merged**
