### PR TITLE
added unit test for openBrowser API

### PR DESCRIPTION
**Pull request by Manikkumar1988**

### CODE REVIEW

**Comment by NivedhaSenthil** [comment]
@Manikkumar1988  can you please sign the CLA ?

**Comment by Manikkumar1988** [comment]
@NivedhaSenthil I have agreed the CLA, but it's not reflecting here, do I need to any thing specific, apart from clicking "I Agree"?

**Comment by negiDharmendra** [comment]
@gaugebot recheck

**Comment by Manikkumar1988** [comment]
@gaugebot recheck the pull request.

**Pull request merged**
